/**
 * CI Workflow Generator
 *
 * Generates a multi-job CI pipeline that runs on every PR:
 *   Job 1: quality-gates — TypeScript check, lint, build (only non-null commands)
 *   Job 2: unit-tests — Run unit tests (if configured)
 *   Job 3: e2e — Install Playwright browsers + run E2E (if configured)
 *
 * Adapts per repo based on ci{} config in RepoConfig.
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateCI(repo: RepoConfig): string {
  const { ci } = repo;

  // Build quality gate steps - only include non-null commands
  const qualitySteps: string[] = [];
  if (ci.typeCheckCommand) qualitySteps.push(`      - name: TypeScript check\n        run: npx ${ci.typeCheckCommand}`);
  if (ci.lintCommand) qualitySteps.push(`      - name: Lint\n        run: npx ${ci.lintCommand}`);
  if (ci.buildCommand) qualitySteps.push(`      - name: Build\n        run: npx ${ci.buildCommand}`);

  // Build jobs
  let jobs = `  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'
      - run: npm ci
${qualitySteps.join('\n')}`;

  if (ci.unitTestCommand) {
    jobs += `\n\n  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: quality-gates
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'
      - run: npm ci
      - name: Run unit tests
        run: npx ${ci.unitTestCommand}`;
  }

  if (ci.e2e) {
    jobs += `\n\n  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: quality-gates${ci.e2e.blocking ? '' : '\n    continue-on-error: true'}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'
      - run: npm ci
      - name: Install Playwright browsers
        run: ${ci.e2e.installCommand}
      - name: Run E2E tests
        run: ${ci.e2e.command}`;
  }

  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
name: CI Quality Gates

on:
  pull_request:
    branches: [${repo.defaultBranch}]
  push:
    branches: [${repo.defaultBranch}]

concurrency:
  group: ci-\${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
${jobs}
`;}

