/**
 * CI Workflow Generator
 *
 * Generates a multi-job CI pipeline that runs on every PR:
 *   Job 1: quality-gates — TypeScript check, lint, build (only non-null commands)
 *   Job 2: unit-tests — Run unit tests (if configured)
 *
 * E2E tests are handled by copilot-full-automation.yml Phase 3.5 (scoped to changed files).
 * They are NOT included in ci.yml to avoid duplicate unscoped runs.
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateCI(repo: RepoConfig): string {
  const { ci } = repo;

  // Build quality gate steps - only include non-null commands
  const qualitySteps: string[] = [];
  if (ci.typeCheckCommand) qualitySteps.push(`      - name: Type check\n        run: npm run type-check`);
  if (ci.lintCommand) qualitySteps.push(`      - name: Lint\n        run: npm run lint`);
  if (ci.buildCommand) qualitySteps.push(`      - name: Build\n        run: npm run build`);

  // Build jobs
  let jobs = `  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'
      - run: npm ci
${qualitySteps.join('\n')}`;

  if (ci.unitTestCommand) {
    jobs += `\n\n  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: quality-gates
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'
      - run: npm ci
      - name: Unit tests
        run: npm test`;
  }

  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
# E2E tests run via copilot-full-automation.yml Phase 3.5 (scoped to changed files)
name: CI Quality Gates

on:
  pull_request:
    branches: [${repo.defaultBranch}]
  push:
    branches: [${repo.defaultBranch}]

concurrency:
  group: ci-\${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
${jobs}
`;}

