/**
 * CI Workflow Generator
 *
 * Generates a quality-gate CI pipeline that runs on every PR:
 *   - TypeScript check (npx tsc --noEmit)
 *   - ESLint (npm run lint)
 *   - Build (npm run build)
 *   - E2E tests (if enabled)
 *
 * Adapts node version and E2E command per repo config.
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateCI(repo: RepoConfig): string {
  const e2eStep = repo.hasE2E
    ? `
      - name: Run E2E tests
        run: ${repo.e2eCommand}`
    : '';

  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
name: CI Quality Gates

on:
  pull_request:
    branches: [${repo.defaultBranch}]
  push:
    branches: [${repo.defaultBranch}]

permissions:
  contents: read

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: ESLint
        run: npm run lint

      - name: Build
        run: npm run build${e2eStep}
`;
}
