/**
 * Copilot Full Automation Pipeline — 30x Generator
 *
 * Complete 8-phase self-healing pipeline:
 *   Phase 1: Issue triage → assign Copilot coding agent → create branch + draft PR
 *   Phase 2: Promote draft → ready for review → request Copilot code review
 *   Phase 3: Quality validation (tsc + lint + build) + DB migration detection
 *   Phase 4: Implement Copilot review suggestions (feedback loop → re-trigger Copilot)
 *   Phase 5: Auto-approve & squash merge (BLOCKED for DB migration PRs)
 *   Phase 6: DB migration firewall (manual merge required)
 *   Phase 7: Failure handling → re-assign Copilot to fix (self-healing loop)
 *   Phase 8: Post-merge cleanup → update issues → chain to next issue
 *
 * Adapts node version, Supabase project ID, and label triggers per repo config.
 */
import type { RepoConfig } from '../config/repo-registry.js';

/**
 * Generates the optional Phase 3.5 E2E validation job YAML block.
 * Returns empty string for repos without E2E tests configured.
 */
function generateE2EJobYaml(repo: RepoConfig): string {
  return `
  # =========================================================================
  # PHASE 3.5: E2E VALIDATION (optional, non-blocking)
  # Runs end-to-end tests after quality checks pass — does NOT block merge
  # =========================================================================
  e2e-validation:
    name: "Phase 3.5: E2E Validation"
    runs-on: ubuntu-latest
    needs: validate-pr
    continue-on-error: true
    if: |
      needs.validate-pr.outputs.all_checks_passed == 'true'
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        id: e2e
        run: ${repo.e2eCommand}
        continue-on-error: true

      - name: Comment E2E results
        if: always()
        uses: actions/github-script@v7
        env:
          E2E_STATUS: \${{ steps.e2e.outcome }}
        with:
          script: |
            const status = process.env.E2E_STATUS;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: [
                '## Phase 3.5: E2E Validation (Non-Blocking)',
                '',
                '| Check | Status |',
                '|-------|--------|',
                \`| E2E Tests | \${status === 'success' ? 'Pass' : 'FAIL (non-blocking)'} |\`,
                '',
                status !== 'success'
                  ? 'E2E tests did not pass. This is **non-blocking** — auto-merge can still proceed.'
                  : 'All E2E tests passed.',
                '',
                '*UGWTF 30x Pipeline — Phase 3.5 complete*'
              ].join('\\n')
            });`;
}

export function generateCopilotFullAutomation(repo: RepoConfig): string {
  // Build the manual-merge comment for DB migration PRs
  const dbMergeInstructions = repo.supabaseProjectId
    ? [
        `'1. Apply migration SQL via Supabase Dashboard SQL Editor',`,
        `'2. Regenerate types: \\\`npx supabase gen types typescript --project-id ${repo.supabaseProjectId} > ${repo.supabaseTypesPath}\\\`',`,
        `'3. Deploy Edge Functions if needed',`,
        `'4. Run quality gates: \\\`npx tsc --noEmit && npm run lint && npm run build\\\`',`,
        `'5. Merge PR manually after verification',`,
      ].join('\n                ')
    : [
        `'1. Review migration SQL carefully',`,
        `'2. Apply migration manually',`,
        `'3. Run quality gates: \\\`npx tsc --noEmit && npm run lint && npm run build\\\`',`,
        `'4. Merge PR manually after verification',`,
      ].join('\n                ');

  // Phase 3.5: Optional E2E validation job (only when repo.hasE2E is true)
  const e2eJob = repo.hasE2E && repo.e2eCommand
    ? generateE2EJobYaml(repo)
    : '';

  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
# 30x Copilot Full Automation Pipeline — 8-phase self-healing loop
name: Copilot Full Automation Pipeline — 30x

on:
  issues:
    types: [opened, labeled]
  pull_request_target:
    types: [opened, synchronize, ready_for_review, closed]
    branches:
      - ${repo.defaultBranch}
      - 'feature/**'
      - 'copilot/**'
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number

concurrency:
  group: copilot-automation-\${{ github.event.pull_request.number || github.event.issue.number || github.run_id }}
  cancel-in-progress: false

jobs:
  # =========================================================================
  # PHASE 1: ISSUE TRIAGE & COPILOT ASSIGNMENT
  # Issue labeled → check existing PRs → assign Copilot → create branch + draft PR
  # =========================================================================
  trigger-pr-creation:
    name: "Phase 1: Issue Triage & Copilot Assignment"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' &&
      (contains(github.event.issue.labels.*.name, 'automation:full') ||
       contains(github.event.issue.labels.*.name, 'automation:copilot') ||
       contains(github.event.issue.labels.*.name, 'agent:copilot'))
    permissions:
      issues: write
      contents: write
      pull-requests: write

    outputs:
      should_create_pr: \${{ steps.check.outputs.should_create }}
      issue_number: \${{ steps.check.outputs.issue_number }}

    steps:
      - name: Check if PR already exists
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });
            const linkedPR = prs.find(pr =>
              pr.body && (
                pr.body.includes(\`Fixes #\${issue_number}\`) ||
                pr.body.includes(\`Closes #\${issue_number}\`) ||
                pr.body.includes(\`Resolves #\${issue_number}\`)
              )
            );
            if (linkedPR) {
              core.setOutput('should_create', 'false');
              core.setOutput('issue_number', issue_number);
              console.log(\`PR #\${linkedPR.number} already linked to issue #\${issue_number}\`);
            } else {
              core.setOutput('should_create', 'true');
              core.setOutput('issue_number', issue_number);
            }

      - name: Assign Copilot coding agent
        if: steps.check.outputs.should_create == 'true'
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: \${{ steps.check.outputs.issue_number }}
        with:
          script: |
            // COPILOT ASSIGNMENT API WORKAROUND
            // The REST API call addAssignees({assignees: ['copilot']}) works
            // reliably within GitHub Actions context but may silently fail
            // via external API calls (gh CLI, MCP tools):
            //   - gh issue edit --add-assignee @copilot → "user not found"
            //   - gh api POST .../assignees → 200 OK but no actual assignment
            // Fallback strategies (priority order):
            //   1. This workflow (GitHub Actions context) — PREFERRED
            //   2. UGWTF CLI copilotAssignAgent — uses Octokit directly
            //   3. Manual: workflow_dispatch trigger on this workflow
            const issueNumber = parseInt(process.env.ISSUE_NUMBER);
            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                assignees: ['copilot']
              });
              console.log(\`Copilot assigned to issue #\${issueNumber}\`);
            } catch (err) {
              core.warning(\`Copilot assignment failed: \${err.message}. Use workflow_dispatch or UGWTF CLI as fallback.\`);
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: [
                '## 30x Copilot Full Automation Activated',
                '',
                'Copilot coding agent has been assigned to this issue.',
                '',
                '**8-Phase Pipeline:**',
                '1. Copilot coding agent — **Assigned**',
                '2. Draft PR → Ready for Review — *automatic*',
                '3. Quality checks — TypeScript + ESLint + Build',
                '4. Copilot code review — *auto-requested*',
                '5. Review feedback → Copilot re-implements — *self-healing loop*',
                '6. Auto-approve & merge — squash (non-DB PRs)',
                '7. DB migration firewall — manual merge if needed',
                '8. Post-merge cleanup — issues updated automatically',
                '',
                '*Copilot will create a PR and push commits. The pipeline handles the rest.*'
              ].join('\\n')
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: ['automation:in-progress']
            });

      - name: Create branch and placeholder PR (fallback)
        if: steps.check.outputs.should_create == 'true'
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: \${{ steps.check.outputs.issue_number }}
          ISSUE_TITLE: \${{ github.event.issue.title }}
        with:
          script: |
            const issueNumber = parseInt(process.env.ISSUE_NUMBER);
            const issueTitle = process.env.ISSUE_TITLE;
            const branchName = \`copilot/issue-\${issueNumber}\`;
            try {
              const { data: ref } = await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/${repo.defaultBranch}'
              });
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: \`refs/heads/\${branchName}\`,
                sha: ref.object.sha
              });
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: \`[Auto] \${issueTitle}\`,
                head: branchName,
                base: '${repo.defaultBranch}',
                body: \`Fixes #\${issueNumber}\\n\\nAutomated PR — Copilot will push implementation commits.\\n\\n*Managed by UGWTF 30x Pipeline*\`,
                draft: true
              });
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['automation:copilot']
              });
            } catch (error) {
              console.log(\`Branch may already exist: \${error.message}\`);
            }

  # =========================================================================
  # PHASE 2: PROMOTE DRAFT → READY FOR REVIEW + REQUEST COPILOT REVIEW
  # When Copilot pushes commits to a draft PR, promote it and request review
  # =========================================================================
  promote-and-review:
    name: "Phase 2: Promote Draft & Request Review"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.action == 'synchronize' &&
      github.event.pull_request.draft == true &&
      (contains(github.event.pull_request.labels.*.name, 'automation:copilot') ||
       startsWith(github.event.pull_request.head.ref, 'copilot/'))
    permissions:
      contents: read
      pull-requests: write
      actions: write

    steps:
      - name: Check if PR has real implementation
        id: check-ready
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              per_page: 100
            });
            const hasImplementation = files.length > 0 && files.some(f =>
              f.filename.endsWith('.ts') || f.filename.endsWith('.tsx') ||
              f.filename.endsWith('.js') || f.filename.endsWith('.jsx') ||
              f.filename.endsWith('.css') || f.filename.endsWith('.json') ||
              f.filename.endsWith('.yml') || f.filename.endsWith('.yaml') ||
              f.filename.endsWith('.md') || f.filename.endsWith('.sql')
            );
            core.setOutput('ready', hasImplementation ? 'true' : 'false');
            console.log(\`PR has \${files.length} changed files, implementation: \${hasImplementation}\`);

      - name: Convert draft to ready for review
        if: steps.check-ready.outputs.ready == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                draft: false
              });
              console.log('Draft PR promoted to ready for review');
            } catch (err) {
              console.log(\`Could not promote draft: \${err.message}\`);
            }

      - name: Request Copilot code review
        if: steps.check-ready.outputs.ready == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: ['copilot']
              });
              console.log('Copilot code review requested');
            } catch (err) {
              console.log(\`Could not request Copilot review: \${err.message}\`);
            }

      - name: Approve pending workflow runs
        if: steps.check-ready.outputs.ready == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                status: 'action_required',
                per_page: 10
              });
              const prRuns = runs.workflow_runs.filter(r =>
                r.head_sha === context.payload.pull_request.head.sha
              );
              for (const run of prRuns) {
                await github.rest.actions.approveWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                });
                console.log(\`Approved workflow run \${run.id}\`);
              }
            } catch (err) {
              console.log(\`Workflow approval skipped: \${err.message}\`);
            }

      - name: Comment promotion status
        if: steps.check-ready.outputs.ready == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: [
                '## Phase 2: Ready for Review',
                '',
                '| Action | Status |',
                '|--------|--------|',
                '| Draft → Ready | Promoted |',
                '| Copilot Code Review | Requested |',
                '| Workflow Approval | Checked |',
                '',
                'Quality checks will run next. Copilot will review the implementation.',
                '',
                '*UGWTF 30x Pipeline — Phase 2 complete*'
              ].join('\\n')
            });

  # =========================================================================
  # PHASE 3: QUALITY VALIDATION (runs on PR)
  # TypeScript + ESLint + Build + DB migration detection
  # =========================================================================
  validate-pr:
    name: "Phase 3: Quality Validation"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      (github.event.action == 'ready_for_review' || github.event.action == 'synchronize') &&
      github.event.pull_request.draft == false &&
      (contains(github.event.pull_request.labels.*.name, 'automation:copilot') ||
       contains(github.event.pull_request.labels.*.name, 'automation:full') ||
       startsWith(github.event.pull_request.head.ref, 'copilot/'))
    permissions:
      contents: read
      pull-requests: write

    outputs:
      all_checks_passed: \${{ steps.summary.outputs.passed }}
      has_db_migration: \${{ steps.detect-db.outputs.has_db }}
      linked_issue: \${{ steps.detect-db.outputs.linked_issue }}
      tsc_errors: \${{ steps.typescript.outputs.errors }}
      lint_errors: \${{ steps.eslint.outputs.errors }}
      build_errors: \${{ steps.build.outputs.errors }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.sha }}

      - name: Detect DB migrations in changed files
        id: detect-db
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              per_page: 100
            });
            const hasDB = files.some(f =>
              f.filename.includes('supabase/migrations') ||
              f.filename.endsWith('.sql')
            );
            core.setOutput('has_db', hasDB ? 'true' : 'false');

            const body = context.payload.pull_request.body || '';
            const issueMatch = body.match(/(?:Fixes|Closes|Resolves)\\s+#(\\d+)/i);
            core.setOutput('linked_issue', issueMatch ? issueMatch[1] : '');

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        id: typescript
        run: |
          set +e
          TSC_OUTPUT=$(npx tsc --noEmit 2>&1)
          TSC_EXIT=$?
          set -e
          echo "$TSC_OUTPUT"
          TSC_ERRORS=$(echo "$TSC_OUTPUT" | grep -E "error TS" | head -20)
          {
            echo "errors<<UGWTF_EOF"
            echo "$TSC_ERRORS"
            echo "UGWTF_EOF"
          } >> $GITHUB_OUTPUT
          exit $TSC_EXIT
        continue-on-error: true

      - name: Run ESLint
        id: eslint
        run: |
          set +e
          LINT_OUTPUT=$(npm run lint 2>&1)
          LINT_EXIT=$?
          set -e
          echo "$LINT_OUTPUT"
          LINT_ERRORS=$(echo "$LINT_OUTPUT" | grep -E "[0-9]+ error|[0-9]+ warning" | head -20)
          {
            echo "errors<<UGWTF_EOF"
            echo "$LINT_ERRORS"
            echo "UGWTF_EOF"
          } >> $GITHUB_OUTPUT
          exit $LINT_EXIT
        continue-on-error: true

      - name: Run Build
        id: build
        run: |
          set +e
          BUILD_OUTPUT=$(npm run build 2>&1)
          BUILD_EXIT=$?
          set -e
          echo "$BUILD_OUTPUT"
          BUILD_ERRORS=$(echo "$BUILD_OUTPUT" | grep -Ei "error|failed" | head -20)
          {
            echo "errors<<UGWTF_EOF"
            echo "$BUILD_ERRORS"
            echo "UGWTF_EOF"
          } >> $GITHUB_OUTPUT
          exit $BUILD_EXIT
        continue-on-error: true

      - name: Determine overall status
        id: summary
        run: |
          if [[ "\${{ steps.typescript.outcome }}" == "success" ]] && \\
             [[ "\${{ steps.eslint.outcome }}" == "success" ]] && \\
             [[ "\${{ steps.build.outcome }}" == "success" ]]; then
            echo "passed=true" >> $GITHUB_OUTPUT
          else
            echo "passed=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment validation results
        uses: actions/github-script@v7
        env:
          TS_STATUS: \${{ steps.typescript.outcome }}
          LINT_STATUS: \${{ steps.eslint.outcome }}
          BUILD_STATUS: \${{ steps.build.outcome }}
          OVERALL: \${{ steps.summary.outputs.passed }}
          HAS_DB: \${{ steps.detect-db.outputs.has_db }}
        with:
          script: |
            const ts = process.env.TS_STATUS;
            const lint = process.env.LINT_STATUS;
            const build = process.env.BUILD_STATUS;
            const passed = process.env.OVERALL === 'true';
            const hasDB = process.env.HAS_DB === 'true';
            const body = [
              '## Phase 3: Quality Validation Results',
              '',
              '| Check | Status |',
              '|-------|--------|',
              \`| TypeScript | \${ts === 'success' ? 'Pass' : 'FAIL'} |\`,
              \`| ESLint | \${lint === 'success' ? 'Pass' : 'FAIL'} |\`,
              \`| Build | \${build === 'success' ? 'Pass' : 'FAIL'} |\`,
              \`| DB Migration | \${hasDB ? 'DETECTED — manual merge required' : 'None'} |\`,
              '',
              passed && !hasDB
                ? '**All checks passed** — proceeding to auto-approval & merge'
                : passed && hasDB
                ? '**Checks passed** but DB migration detected — **manual merge required**'
                : '**Checks failed** — Copilot will be re-assigned to fix',
              '',
              '*UGWTF 30x Pipeline — Phase 3 complete*'
            ].join('\\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
${e2eJob}
  # =========================================================================
  # PHASE 4: IMPLEMENT COPILOT REVIEW SUGGESTIONS (self-healing feedback loop)
  # When Copilot code review requests changes → re-assign Copilot to implement
  # =========================================================================
  implement-review-feedback:
    name: "Phase 4: Implement Review Suggestions"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'changes_requested' &&
      (contains(github.event.pull_request.labels.*.name, 'automation:copilot') ||
       startsWith(github.event.pull_request.head.ref, 'copilot/'))
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - name: Analyze review suggestions
        id: analyze
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              per_page: 100
            });

            const reviewComments = comments.filter(c =>
              c.pull_request_review_id === context.payload.review.id
            );
            const suggestions = reviewComments.filter(c =>
              c.body && c.body.includes('\`\`\`suggestion')
            );
            const totalComments = reviewComments.length;
            const suggestionCount = suggestions.length;

            core.setOutput('total_comments', totalComments.toString());
            core.setOutput('suggestion_count', suggestionCount.toString());
            core.setOutput('reviewer', context.payload.review.user.login);
            console.log(\`Review has \${totalComments} comments, \${suggestionCount} suggestions\`);

      - name: Re-assign Copilot to implement fixes
        uses: actions/github-script@v7
        env:
          TOTAL_COMMENTS: \${{ steps.analyze.outputs.total_comments }}
          SUGGESTION_COUNT: \${{ steps.analyze.outputs.suggestion_count }}
          REVIEWER: \${{ steps.analyze.outputs.reviewer }}
        with:
          script: |
            const totalComments = parseInt(process.env.TOTAL_COMMENTS);
            const suggestionCount = parseInt(process.env.SUGGESTION_COUNT);
            const reviewer = process.env.REVIEWER;
            const prNumber = context.payload.pull_request.number;

            const body = context.payload.pull_request.body || '';
            const issueMatch = body.match(/(?:Fixes|Closes|Resolves)\\s+#(\\d+)/i);
            const linkedIssue = issueMatch ? parseInt(issueMatch[1]) : null;

            if (linkedIssue) {
              try {
                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: linkedIssue,
                  assignees: ['copilot']
                });
              } catch (err) {
                console.log(\`Could not re-assign Copilot: \${err.message}\`);
              }
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: [
                '## Phase 4: Review Feedback — Self-Healing Loop',
                '',
                \`Code review by **\${reviewer}** requested changes.\`,
                '',
                '| Metric | Count |',
                '|--------|-------|',
                \`| Review comments | \${totalComments} |\`,
                \`| Suggested changes | \${suggestionCount} |\`,
                '',
                '**Action:** Copilot coding agent has been re-assigned to implement the review feedback.',
                'New commits will re-trigger quality validation (Phase 3).',
                '',
                '*UGWTF 30x Pipeline — Phase 4: feedback loop activated*'
              ].join('\\n')
            });

  # =========================================================================
  # PHASE 5: AUTO-APPROVE & MERGE (BLOCKED for DB migration PRs)
  # All checks pass + no DB migration → approve + squash merge
  # =========================================================================
  auto-merge:
    name: "Phase 5: Auto-Approve & Merge"
    runs-on: ubuntu-latest
    needs: validate-pr
    if: |
      needs.validate-pr.outputs.all_checks_passed == 'true' &&
      needs.validate-pr.outputs.has_db_migration == 'false'
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "\${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Comment merge status
        uses: actions/github-script@v7
        with:
          script: |
            const now = new Date().toISOString();
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: [
                '## Phase 5: Auto-Approve & Merge',
                '',
                '| Action | Status |',
                '|--------|--------|',
                '| Auto-approve | Done |',
                '| Auto-merge | Enabled (squash) |',
                '',
                'PR will merge automatically once all branch protection checks pass.',
                '',
                '<details><summary>Audit Trail</summary>',
                '',
                '| Field | Value |',
                '|-------|-------|',
                \`| Run ID | \${context.runId} |\`,
                \`| Actor | \${context.actor} |\`,
                \`| Head SHA | \${context.payload.pull_request.head.sha.substring(0, 7)} |\`,
                \`| Timestamp | \${now} |\`,
                '| Strategy | squash-merge |',
                '',
                '</details>',
                '',
                '*UGWTF 30x Pipeline — Phase 5 complete*'
              ].join('\\n')
            });

  # =========================================================================
  # PHASE 6: DB MIGRATION FIREWALL (manual merge required)
  # All checks pass but DB migration detected → block auto-merge
  # =========================================================================
  db-migration-hold:
    name: "Phase 6: DB Migration Firewall"
    runs-on: ubuntu-latest
    needs: validate-pr
    if: |
      needs.validate-pr.outputs.all_checks_passed == 'true' &&
      needs.validate-pr.outputs.has_db_migration == 'true'
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Post manual merge instructions
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: [
                '## Phase 6: DB Migration Firewall — Manual Merge Required',
                '',
                'Quality checks passed but this PR contains database migrations.',
                'Auto-merge is **disabled** for safety.',
                '',
                '**Manual steps required:**',
                ${dbMergeInstructions}
                '',
                '*UGWTF 30x Pipeline — Phase 6: firewall active*'
              ].join('\\n')
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['database', 'needs-review']
            });

  # =========================================================================
  # PHASE 7: FAILURE HANDLING → RE-ASSIGN COPILOT (self-healing)
  # Quality checks failed → count retries, provide error context, or escalate
  # =========================================================================
  handle-failure:
    name: "Phase 7: Failure Handling & Auto-Retry"
    runs-on: ubuntu-latest
    needs: validate-pr
    if: needs.validate-pr.outputs.all_checks_passed == 'false'
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Count previous fix attempts
        id: count-attempts
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              per_page: 100
            });
            const attempts = comments.filter(c =>
              c.body && c.body.includes('UGWTF Fix Attempt')
            ).length;
            core.setOutput('attempt_number', String(attempts + 1));
            core.setOutput('should_give_up', attempts >= 2 ? 'true' : 'false');

      - name: Escalate to human (max retries exceeded)
        if: steps.count-attempts.outputs.should_give_up == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: [
                '## Phase 7: Max Retries Exceeded — Human Review Required',
                '',
                'Copilot has attempted **3 fix cycles** but quality checks still fail.',
                '',
                '**Automated self-healing has been disabled for this PR.**',
                '',
                'A human developer must review and resolve the remaining issues.',
                '',
                '*UGWTF 30x Pipeline — Phase 7: escalated to human*'
              ].join('\\n')
            });
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: 'automation:in-progress'
              });
            } catch (e) {}
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['needs-review', 'needs-human-review']
            });

      - name: Post structured fix request and re-assign Copilot
        if: steps.count-attempts.outputs.should_give_up == 'false'
        uses: actions/github-script@v7
        env:
          LINKED_ISSUE: \${{ needs.validate-pr.outputs.linked_issue }}
          TSC_ERRORS: \${{ needs.validate-pr.outputs.tsc_errors }}
          LINT_ERRORS: \${{ needs.validate-pr.outputs.lint_errors }}
          BUILD_ERRORS: \${{ needs.validate-pr.outputs.build_errors }}
          ATTEMPT: \${{ steps.count-attempts.outputs.attempt_number }}
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const linkedIssue = process.env.LINKED_ISSUE;
            const attempt = process.env.ATTEMPT;
            const tscErrors = process.env.TSC_ERRORS || '';
            const lintErrors = process.env.LINT_ERRORS || '';
            const buildErrors = process.env.BUILD_ERRORS || '';

            if (linkedIssue) {
              try {
                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: parseInt(linkedIssue),
                  assignees: ['copilot']
                });
              } catch (err) {
                console.log(\`Could not re-assign Copilot: \${err.message}\`);
              }
            }

            const sections = [];
            if (tscErrors.trim()) {
              sections.push('### TypeScript Errors\\n<pre>' + tscErrors + '</pre>');
            }
            if (lintErrors.trim()) {
              sections.push('### ESLint Errors\\n<pre>' + lintErrors + '</pre>');
            }
            if (buildErrors.trim()) {
              sections.push('### Build Errors\\n<pre>' + buildErrors + '</pre>');
            }
            if (sections.length === 0) {
              sections.push('*No specific error output captured — check workflow logs.*');
            }

            const isLastAttempt = attempt === '2';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: [
                \`## UGWTF Fix Attempt \${attempt}/3 — Quality Checks Failed\`,
                '',
                'The following errors must be fixed:',
                '',
                ...sections,
                '',
                \`**Retry \${attempt} of 3** — Copilot has been re-assigned to fix.\`,
                isLastAttempt ? '**Last automatic attempt** — next failure escalates to human review.' : '',
                '',
                '*UGWTF 30x Pipeline — Phase 7: self-healing loop*'
              ].filter(Boolean).join('\\n')
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['needs-review']
            });

  # =========================================================================
  # PHASE 8: POST-MERGE CLEANUP & ISSUE CHAIN
  # PR merged → update linked issues → close completed → chain next issue
  # =========================================================================
  post-merge-cleanup:
    name: "Phase 8: Post-Merge Cleanup"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      (contains(github.event.pull_request.labels.*.name, 'automation:copilot') ||
       startsWith(github.event.pull_request.head.ref, 'copilot/'))
    permissions:
      issues: write
      contents: read

    steps:
      - name: Update linked issues and chain
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;

            const issueMatches = [...body.matchAll(/(?:Fixes|Closes|Resolves)\\s+#(\\d+)/gi)];
            const completedIssues = [];

            for (const match of issueMatches) {
              const issueNumber = parseInt(match[1]);
              try {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  labels: ['automation:completed']
                });
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  name: 'automation:in-progress'
                }).catch(() => {});

                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  state: 'closed',
                  state_reason: 'completed'
                });

                completedIssues.push(issueNumber);
              } catch (err) {
                console.log(\`Could not update issue #\${issueNumber}: \${err.message}\`);
              }
            }

            const openIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'agent:copilot,automation:copilot',
              per_page: 5,
              sort: 'created',
              direction: 'asc'
            });

            const nextIssue = openIssues.data.find(i =>
              !i.pull_request &&
              !i.labels.some(l => l.name === 'automation:in-progress')
            );

            let chainMessage = '';
            if (nextIssue) {
              try {
                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: nextIssue.number,
                  assignees: ['copilot']
                });
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: nextIssue.number,
                  labels: ['automation:in-progress']
                });
                chainMessage = \`**Chain:** Copilot auto-assigned to next issue #\${nextIssue.number}: \${nextIssue.title}\`;

                // Handoff context: post minimal context on the chained issue
                // so the next agent knows what just changed (point to artifacts, not source)
                const { data: prFiles } = await github.rest.pulls.listFiles({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  per_page: 30
                });
                const changedPaths = prFiles.map(f => f.filename).slice(0, 15);
                const handoffBody = [
                  '## Handoff Context from PR #' + prNumber,
                  '',
                  \`Previous PR merged: **\${prTitle}**\`,
                  '',
                  '**Files changed** (review these before starting):',
                  ...changedPaths.map(p => \`- \\\`\${p}\\\`\`),
                  prFiles.length > 15 ? \`- ... and \${prFiles.length - 15} more\` : '',
                  '',
                  '**Quality gates passed:** TypeScript, ESLint, Build',
                  '',
                  '*Handoff generated by UGWTF 30x Pipeline*'
                ].filter(Boolean).join('\\n');
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: nextIssue.number,
                  body: handoffBody
                });
              } catch (err) {
                console.log(\`Could not chain to issue #\${nextIssue.number}: \${err.message}\`);
              }
            }

            const now = new Date().toISOString();
            if (completedIssues.length > 0 || chainMessage) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: [
                  '## Phase 8: Post-Merge Cleanup',
                  '',
                  \`PR #\${prNumber} merged successfully.\`,
                  '',
                  completedIssues.length > 0
                    ? \`**Completed issues:** \${completedIssues.map(n => \`#\${n}\`).join(', ')}\`
                    : '',
                  chainMessage,
                  '',
                  '<details><summary>Audit Trail</summary>',
                  '',
                  '| Field | Value |',
                  '|-------|-------|',
                  \`| Run ID | \${context.runId} |\`,
                  \`| Actor | \${context.actor} |\`,
                  \`| Merged SHA | \${context.payload.pull_request.merge_commit_sha?.substring(0, 7) ?? 'N/A'} |\`,
                  \`| Timestamp | \${now} |\`,
                  \`| Issues Closed | \${completedIssues.length} |\`,
                  '',
                  '</details>',
                  '',
                  '*UGWTF 30x Pipeline — all phases complete*'
                ].filter(Boolean).join('\\n')
              });
            }
`;
}
