/**
 * Copilot Full Automation Pipeline Generator
 *
 * 5-phase pipeline ported from damieus-com-migration gold standard:
 *   Phase 1: Immediate PR creation when issue labeled
 *   Phase 2: Detect DB migrations in changed files (firewall gate)
 *   Phase 3: Quality validation on PR (tsc + lint + build)
 *   Phase 4: Auto-approve & merge (BLOCKED for DB migration PRs)
 *   Phase 5: Failure handling with actionable comments
 *
 * Adapts node version, Supabase project ID, and label triggers per repo config.
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateCopilotFullAutomation(repo: RepoConfig): string {
  // Build the manual-merge comment for DB migration PRs
  const dbMergeInstructions = repo.supabaseProjectId
    ? [
        `'1. Apply migration SQL via Supabase Dashboard SQL Editor',`,
        `'2. Regenerate types: \\\`npx supabase gen types typescript --project-id ${repo.supabaseProjectId} > ${repo.supabaseTypesPath}\\\`',`,
        `'3. Deploy Edge Functions if needed',`,
        `'4. Merge PR manually after verification',`,
      ].join('\n                ')
    : [
        `'1. Review migration SQL carefully',`,
        `'2. Apply migration manually',`,
        `'3. Merge PR manually after verification',`,
      ].join('\n                ');

  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
name: Copilot Full Automation Pipeline

on:
  issues:
    types: [opened, labeled]
  pull_request_target:
    types: [opened, synchronize, ready_for_review]
    branches:
      - ${repo.defaultBranch}
      - 'feature/**'
      - 'copilot/**'
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number

jobs:
  # =========================================================================
  # PHASE 1: IMMEDIATE PR CREATION
  # =========================================================================
  trigger-pr-creation:
    name: Immediate PR Creation
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' &&
      (contains(github.event.issue.labels.*.name, 'automation:full') ||
       contains(github.event.issue.labels.*.name, 'automation:copilot') ||
       contains(github.event.issue.labels.*.name, 'agent:copilot'))
    permissions:
      issues: write
      contents: write
      pull-requests: write

    outputs:
      should_create_pr: \${{ steps.check.outputs.should_create }}
      issue_number: \${{ steps.check.outputs.issue_number }}

    steps:
      - name: Check if PR already exists
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });
            const linkedPR = prs.find(pr =>
              pr.body && (
                pr.body.includes(\`Fixes #\${issue_number}\`) ||
                pr.body.includes(\`Closes #\${issue_number}\`) ||
                pr.body.includes(\`Resolves #\${issue_number}\`)
              )
            );
            if (linkedPR) {
              core.setOutput('should_create', 'false');
              core.setOutput('issue_number', issue_number);
            } else {
              core.setOutput('should_create', 'true');
              core.setOutput('issue_number', issue_number);
            }

      - name: Assign Copilot coding agent
        if: steps.check.outputs.should_create == 'true'
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: \${{ steps.check.outputs.issue_number }}
        with:
          script: |
            const issueNumber = parseInt(process.env.ISSUE_NUMBER);
            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                assignees: ['copilot']
              });
            } catch (err) {
              console.log(\`Could not assign Copilot: \${err.message}\`);
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: [
                '**Copilot Full Automation Activated**',
                '',
                'Copilot coding agent has been assigned to this issue.',
                '',
                '**Pipeline:**',
                '- Copilot coding agent: Assigned',
                '- Quality checks: TypeScript + ESLint + Build',
                '- DB migration firewall: Active',
                '- Auto-approve: If checks pass (non-DB PRs only)',
                '- Auto-merge: Enabled (squash)',
                '',
                '*Copilot will create a PR and push commits automatically.*'
              ].join('\\n')
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: ['automation:in-progress']
            });

      - name: Create branch and placeholder PR (fallback)
        if: steps.check.outputs.should_create == 'true'
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: \${{ steps.check.outputs.issue_number }}
          ISSUE_TITLE: \${{ github.event.issue.title }}
        with:
          script: |
            const issueNumber = parseInt(process.env.ISSUE_NUMBER);
            const issueTitle = process.env.ISSUE_TITLE;
            const branchName = \`copilot/issue-\${issueNumber}\`;
            try {
              const { data: ref } = await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/${repo.defaultBranch}'
              });
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: \`refs/heads/\${branchName}\`,
                sha: ref.object.sha
              });
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: \`[Auto] \${issueTitle}\`,
                head: branchName,
                base: '${repo.defaultBranch}',
                body: \`Fixes #\${issueNumber}\\n\\nAutomated PR — Copilot will push implementation commits.\`,
                draft: true
              });
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['automation:copilot']
              });
            } catch (error) {
              console.log(\`Branch may already exist: \${error.message}\`);
            }

  # =========================================================================
  # PHASE 2: QUALITY VALIDATION (runs on PR)
  # Includes DB migration detection for firewall gating
  # =========================================================================
  validate-pr:
    name: Quality Checks
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      (contains(github.event.pull_request.labels.*.name, 'automation:copilot') ||
       contains(github.event.pull_request.labels.*.name, 'automation:full'))
    permissions:
      contents: read
      pull-requests: write

    outputs:
      all_checks_passed: \${{ steps.summary.outputs.passed }}
      has_db_migration: \${{ steps.detect-db.outputs.has_db }}
      linked_issue: \${{ steps.detect-db.outputs.linked_issue }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.sha }}

      - name: Detect DB migrations in changed files
        id: detect-db
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              per_page: 100
            });
            const hasDB = files.some(f =>
              f.filename.includes('supabase/migrations') ||
              f.filename.endsWith('.sql')
            );
            core.setOutput('has_db', hasDB ? 'true' : 'false');

            const body = context.payload.pull_request.body || '';
            const issueMatch = body.match(/(?:Fixes|Closes|Resolves)\\s+#(\\d+)/i);
            core.setOutput('linked_issue', issueMatch ? issueMatch[1] : '');

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        id: typescript
        run: npx tsc --noEmit
        continue-on-error: true

      - name: Run ESLint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Run Build
        id: build
        run: npm run build
        continue-on-error: true

      - name: Determine overall status
        id: summary
        run: |
          if [[ "\${{ steps.typescript.outcome }}" == "success" ]] && \\
             [[ "\${{ steps.eslint.outcome }}" == "success" ]] && \\
             [[ "\${{ steps.build.outcome }}" == "success" ]]; then
            echo "passed=true" >> $GITHUB_OUTPUT
          else
            echo "passed=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment validation results
        uses: actions/github-script@v7
        env:
          TS_STATUS: \${{ steps.typescript.outcome }}
          LINT_STATUS: \${{ steps.eslint.outcome }}
          BUILD_STATUS: \${{ steps.build.outcome }}
          OVERALL: \${{ steps.summary.outputs.passed }}
          HAS_DB: \${{ steps.detect-db.outputs.has_db }}
        with:
          script: |
            const ts = process.env.TS_STATUS;
            const lint = process.env.LINT_STATUS;
            const build = process.env.BUILD_STATUS;
            const passed = process.env.OVERALL === 'true';
            const hasDB = process.env.HAS_DB === 'true';
            const body = [
              '## Automated Quality Check Results',
              '',
              '| Check | Status |',
              '|-------|--------|',
              \`| TypeScript | \${ts === 'success' ? 'Pass' : 'Fail'} |\`,
              \`| ESLint | \${lint === 'success' ? 'Pass' : 'Fail'} |\`,
              \`| Build | \${build === 'success' ? 'Pass' : 'Fail'} |\`,
              \`| DB Migration | \${hasDB ? 'DETECTED — manual merge required' : 'None'} |\`,
              '',
              passed && !hasDB
                ? '✅ **All checks passed** — proceeding to auto-approval'
                : passed && hasDB
                ? '✅ **Checks passed** but DB migration detected — **manual merge required**'
                : '❌ **Checks failed** — manual review required',
              '',
              '*Automated by UGWTF Copilot Full Automation Pipeline*'
            ].join('\\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

  # =========================================================================
  # PHASE 3: AUTO-APPROVE & MERGE (BLOCKED for DB migration PRs)
  # =========================================================================
  auto-merge:
    name: Auto-Approve & Merge
    runs-on: ubuntu-latest
    needs: validate-pr
    if: |
      needs.validate-pr.outputs.all_checks_passed == 'true' &&
      needs.validate-pr.outputs.has_db_migration == 'false'
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "\${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Mark issue completed
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request?.body || '';
            const match = body.match(/(Fixes|Closes|Resolves) #(\\d+)/i);
            if (match) {
              const issueNumber = parseInt(match[2]);
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: ['automation:completed']
              });
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                name: 'automation:in-progress'
              }).catch(() => {});
            }

  # =========================================================================
  # PHASE 4: DB MIGRATION FIREWALL (manual merge required)
  # =========================================================================
  db-migration-hold:
    name: DB Migration — Manual Merge Required
    runs-on: ubuntu-latest
    needs: validate-pr
    if: |
      needs.validate-pr.outputs.all_checks_passed == 'true' &&
      needs.validate-pr.outputs.has_db_migration == 'true'
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Post manual merge instructions
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: [
                '## DB Migration Detected — Manual Merge Required',
                '',
                'Quality checks passed but this PR contains database migrations.',
                'Auto-merge is **disabled** for safety.',
                '',
                '**Manual steps required:**',
                ${dbMergeInstructions}
                '',
                '*Automated by UGWTF Copilot Full Automation Pipeline*'
              ].join('\\n')
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['database', 'needs-review']
            });

  # =========================================================================
  # PHASE 5: FAILURE HANDLING
  # =========================================================================
  handle-failure:
    name: Handle Failure
    runs-on: ubuntu-latest
    needs: validate-pr
    if: needs.validate-pr.outputs.all_checks_passed == 'false'
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Request manual review
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: [
                '## Quality Checks Failed',
                '',
                'Automated quality checks did not pass. Manual review required.',
                '',
                '**Next steps:**',
                '1. Check workflow logs for TypeScript / ESLint / Build errors',
                '2. Fix the issues and push to the PR branch',
                '3. Quality checks will re-run automatically',
              ].join('\\n')
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['needs-review']
            });

            // Also label the linked issue if found
            const body = context.payload.pull_request?.body || '';
            const match = body.match(/(Fixes|Closes|Resolves) #(\\d+)/i);
            if (match) {
              const issueNumber = parseInt(match[2]);
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: ['needs-review']
              });
            }
`;
}
