/**
 * Dependabot Auto-Merge Workflow Generator
 *
 * Triggers on Dependabot PRs:
 *   - Verify actor is dependabot[bot]
 *   - Fetch metadata (patch/minor/major)
 *   - Run quality gates (lint + build)
 *   - Auto-approve + auto-merge for patch/minor
 *   - Warning comment for major updates
 *
 * Based on damieus-com-migration gold-standard (81 lines).
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateDependabotAutoMerge(repo: RepoConfig): string {
  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  check-applicability:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      is_dependabot: \${{ steps.check.outputs.is_dependabot }}
    steps:
      - name: Check if this is a Dependabot PR
        id: check
        run: |
          IS_DEPENDABOT="\${{ github.actor == 'dependabot[bot]' }}"
          if [[ "\$IS_DEPENDABOT" == "true" ]]; then
            echo "is_dependabot=true" >> \$GITHUB_OUTPUT
          else
            echo "is_dependabot=false" >> \$GITHUB_OUTPUT
          fi

  auto-merge:
    runs-on: ubuntu-latest
    needs: check-applicability
    if: needs.check-applicability.outputs.is_dependabot == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Auto-approve PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr review --approve "\$PR_URL"
        env:
          PR_URL: \${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash "\$PR_URL"
        env:
          PR_URL: \${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Add warning comment for major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr comment "\$PR_URL" --body "Major version update detected - Please review this PR manually before merging as it may contain breaking changes."
        env:
          PR_URL: \${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;
}
