/**
 * Prompt Chain Workflow Generator
 *
 * Generates a GitHub Actions workflow file (.github/workflows/prompt-chain.yml)
 * that auto-advances the prompt chain when a chain issue is closed via PR merge.
 *
 * Flow:
 *   PR merges with "Fixes #N" → workflow triggers → reads chain config →
 *   finds closed issue in chain → posts context to next entry → assigns Copilot
 */

/**
 * Generate the prompt-chain.yml workflow content for a given repo.
 */
export function generatePromptChainWorkflow(repoSlug: string): string {
  return `# Auto-generated by UGWTF prompt-chain-workflow generator
# Do not edit manually — regenerate with: ugwtf deploy ${repoSlug.split('/')[1] ?? repoSlug}

name: "Prompt Chain Advance"

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  issues: write
  contents: read

jobs:
  advance-chain:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Advance Prompt Chain
        uses: actions/github-script@v7
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            // Find chain config
            const candidates = [
              'scripts/prompt-chain.json',
              'prompt-chain.json',
              '.github/prompt-chain.json',
            ];

            let configPath = null;
            for (const candidate of candidates) {
              if (fs.existsSync(candidate)) {
                configPath = candidate;
                break;
              }
            }

            if (!configPath) {
              console.log('No prompt-chain.json found — skipping');
              return;
            }

            const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
            const prBody = context.payload.pull_request.body || '';

            // Extract issue numbers from PR body (Fixes #N, Closes #N, Resolves #N)
            const issueRefs = [...prBody.matchAll(/(?:fix(?:es)?|close[sd]?|resolve[sd]?)\\s+#(\\d+)/gi)];
            const closedNumbers = issueRefs.map(m => parseInt(m[1]));

            if (closedNumbers.length === 0) {
              console.log('No issue references found in PR body');
              return;
            }

            console.log('Closed issues from PR:', closedNumbers);

            // Find which chain entry was just closed
            const closedEntry = config.chain.find(e => closedNumbers.includes(e.issue));
            if (!closedEntry) {
              console.log('Closed issues do not match any chain entry — skipping');
              return;
            }

            console.log('Closed chain entry:', closedEntry.prompt, 'position:', closedEntry.position);

            // Find next entry in position order
            const nextEntry = config.chain
              .filter(e => e.position > closedEntry.position && e.issue !== null)
              .sort((a, b) => a.position - b.position)[0];

            if (!nextEntry) {
              console.log('No more entries in the chain — chain complete!');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: closedEntry.issue,
                body: '## Chain Complete\\n\\nAll prompts in the chain have been processed. Great work!'
              });
              return;
            }

            // Check if next issue is already in-progress
            const nextIssue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: nextEntry.issue
            });

            const labels = nextIssue.data.labels.map(l => typeof l === 'string' ? l : l.name);
            if (labels.includes('automation:in-progress')) {
              console.log('Next entry already in-progress — skipping');
              return;
            }

            // Check dependencies are resolved
            for (const dep of nextEntry.depends) {
              const depEntry = config.chain.find(e => e.prompt === dep);
              if (depEntry && depEntry.issue) {
                const depIssue = await github.rest.issues.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: depEntry.issue
                });
                if (depIssue.data.state === 'open') {
                  console.log('Dependency', dep, 'is still open — waiting');
                  return;
                }
              }
            }

            // Post context comment on next issue
            const comment = [
              '## Chain Advancement',
              '',
              'The previous chain entry (' + closedEntry.prompt + ' #' + closedEntry.issue + ') has been completed.',
              'This issue is now the active prompt in the chain.',
              '',
              '**Position**: ' + nextEntry.position + '/' + config.chain.length,
              '**Prompt**: \`' + nextEntry.prompt + '\`',
              '**File**: \`' + nextEntry.file + '\`',
              '**Wave**: ' + nextEntry.wave + ' | **Severity**: ' + nextEntry.severity,
              '',
              'Please read the prompt file and implement the changes described.',
              '',
              '_Automated by UGWTF prompt-chain workflow_',
            ].join('\\n');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: nextEntry.issue,
              body: comment
            });

            // Add in-progress label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: nextEntry.issue,
              labels: ['automation:in-progress']
            });

            // Assign Copilot
            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: nextEntry.issue,
                assignees: ['copilot']
              });
              console.log('Assigned Copilot to #' + nextEntry.issue);
            } catch (assignErr) {
              console.log('Could not assign Copilot (may need MCP):', assignErr.message);
            }

            console.log('Advanced chain to position', nextEntry.position, ':', nextEntry.prompt);
`;
}
