/**
 * Security Audit Workflow Generator
 *
 * Weekly cron + on-push to package files:
 *   - npm audit --json
 *   - Attempt automatic fixes
 *   - Create branch + PR with fixes
 *
 * Based on damieus-com-migration gold-standard (96 lines).
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateSecurityAudit(repo: RepoConfig): string {
  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
name: Security Audit

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    branches:
      - ${repo.defaultBranch}
    paths:
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'

      - name: Run npm audit
        id: audit
        continue-on-error: true
        run: |
          npm audit --json > audit-results.json
          cat audit-results.json
          VULN_COUNT=$(grep -o '"total":[0-9]*' audit-results.json | head -1 | grep -o '[0-9]*' || echo "0")
          echo "vulnerabilities=\$VULN_COUNT" >> \$GITHUB_OUTPUT

      - name: Attempt automatic fix
        id: fix
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm audit fix
          if [[ -n \$(git status -s) ]]; then
            echo "has_fixes=true" >> \$GITHUB_OUTPUT
          else
            echo "has_fixes=false" >> \$GITHUB_OUTPUT
          fi

      - name: Create branch and commit fixes
        if: steps.fix.outputs.has_fixes == 'true'
        id: create_pr
        run: |
          TIMESTAMP=\$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="security/auto-fix-\$TIMESTAMP"
          git checkout -b "\$BRANCH_NAME"
          git add package.json package-lock.json
          git commit -m "fix: automatic security vulnerability fixes"
          git push origin "\$BRANCH_NAME"
          echo "branch=\$BRANCH_NAME" >> \$GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.fix.outputs.has_fixes == 'true'
        run: |
          gh pr create \\
            --title "Security: Automatic vulnerability fixes" \\
            --body "Automated Security Fix

          Vulnerabilities Found: \${{ steps.audit.outputs.vulnerabilities }}

          Changes:
          - Automatic fixes applied using npm audit fix
          - Updated package-lock.json with secure versions

          Generated by Security Audit workflow." \\
            --head "\${{ steps.create_pr.outputs.branch }}" \\
            --base ${repo.defaultBranch}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;
}
