/**
 * Supabase Migration Automation Workflow Generator
 *
 * 3-phase pipeline (PR validation → apply on merge → failure handling):
 *   Phase 1: Validate migration files, check naming, detect destructive ops, comment on PR
 *   Phase 2: Apply migration via REST API + regenerate TypeScript types + create types-update PR
 *   Phase 3: Create P0 incident issue if migration fails
 *
 * Only generated for repos with supabaseProjectId.
 * Based on damieus-com-migration gold-standard (502 lines).
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateSupabaseMigration(repo: RepoConfig): string {
  if (!repo.supabaseProjectId) {
    throw new Error(`supabaseMigration generator requires supabaseProjectId — not set for ${repo.alias}`);
  }

  const urlSecretName = repo.supabaseUrlSecret ?? 'SUPABASE_URL';
  const serviceKeySecretName = repo.supabaseServiceKeySecret ?? 'SUPABASE_SERVICE_ROLE_KEY';
  const typesPath = repo.supabaseTypesPath ?? 'src/integrations/supabase/types.ts';

  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
name: Supabase Migration Automation

on:
  pull_request:
    paths:
      - 'supabase/migrations/*.sql'
      - 'supabase/migrations/*.skip'
    types: [opened, synchronize, ready_for_review]

  push:
    branches: [${repo.defaultBranch}]
    paths:
      - 'supabase/migrations/*.sql'

  workflow_dispatch:
    inputs:
      migration_file:
        description: 'Specific migration file to apply (filename only)'
        required: false
        type: string
      skip_safety_checks:
        description: 'Skip destructive operation checks (USE WITH CAUTION)'
        required: false
        type: boolean
        default: false

jobs:
  # Phase 1: Validate Migration (runs on PR)
  validate-migration:
    name: Validate Migration
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write

    outputs:
      has_destructive_ops: \${{ steps.safety.outputs.has_destructive }}
      migration_files: \${{ steps.detect.outputs.files }}
      validation_passed: \${{ steps.validate.outputs.passed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed migration files
        id: detect
        run: |
          FILES=\$(git diff --name-only origin/${repo.defaultBranch}...HEAD | grep 'supabase/migrations/.*\\.sql\$' || true)
          if [ -z "\$FILES" ]; then
            echo "No migration files changed"
            echo "files=" >> \$GITHUB_OUTPUT
            exit 0
          fi
          echo "Migration files changed:"
          echo "\$FILES"
          FILES_JSON=\$(echo "\$FILES" | jq -R -s -c 'split("\\n") | map(select(length > 0))')
          echo "files=\$FILES_JSON" >> \$GITHUB_OUTPUT

      - name: Check for .skip files
        id: skip-check
        run: |
          SKIP_FILES=\$(find supabase/migrations/ -name "*.skip" || true)
          if [ -n "\$SKIP_FILES" ]; then
            echo "has_skip=true" >> \$GITHUB_OUTPUT
          else
            echo "has_skip=false" >> \$GITHUB_OUTPUT
          fi

      - name: Validate migration file naming
        id: naming
        env:
          FILES: \${{ steps.detect.outputs.files }}
        run: |
          if [ "\$FILES" == "" ] || [ "\$FILES" == "null" ]; then
            exit 0
          fi
          echo "\$FILES" | jq -r '.[]' | while read -r file; do
            filename=\$(basename "\$file")
            if ! echo "\$filename" | grep -qE '^[0-9]{14}_.*\\.sql\$'; then
              echo "Invalid migration filename: \$filename"
              echo "Expected format: YYYYMMDDHHMMSS_name.sql"
              exit 1
            fi
            echo "Valid filename: \$filename"
          done

      - name: Check for destructive operations
        id: safety
        env:
          FILES: \${{ steps.detect.outputs.files }}
        run: |
          if [ "\$FILES" == "" ] || [ "\$FILES" == "null" ]; then
            echo "has_destructive=false" >> \$GITHUB_OUTPUT
            exit 0
          fi
          HAS_DESTRUCTIVE=false
          echo "\$FILES" | jq -r '.[]' | while read -r file; do
            if grep -iE '(DROP\\s+(TABLE|DATABASE|SCHEMA|FUNCTION|TRIGGER)|TRUNCATE|DELETE\\s+FROM\\s+\\w+\\s*;)' "\$file"; then
              echo "DESTRUCTIVE OPERATION DETECTED in \$file"
              HAS_DESTRUCTIVE=true
            fi
          done
          echo "has_destructive=\$HAS_DESTRUCTIVE" >> \$GITHUB_OUTPUT

      - name: Run SQL syntax validation
        id: validate
        env:
          FILES: \${{ steps.detect.outputs.files }}
        run: |
          if [ "\$FILES" == "" ] || [ "\$FILES" == "null" ]; then
            echo "passed=true" >> \$GITHUB_OUTPUT
            exit 0
          fi
          ALL_VALID=true
          echo "\$FILES" | jq -r '.[]' | while read -r file; do
            if ! grep -q ';' "\$file"; then
              echo "Missing semicolon terminator in \$file"
              ALL_VALID=false
            fi
            SINGLE_QUOTES=\$(grep -o "'" "\$file" | wc -l)
            if [ \$((SINGLE_QUOTES % 2)) -ne 0 ]; then
              echo "Unmatched single quotes in \$file"
              ALL_VALID=false
            fi
          done
          echo "passed=\$ALL_VALID" >> \$GITHUB_OUTPUT

      - name: Comment PR with validation results
        uses: actions/github-script@v7
        env:
          HAS_DESTRUCTIVE: \${{ steps.safety.outputs.has_destructive }}
          VALIDATION_PASSED: \${{ steps.validate.outputs.passed }}
          FILES: \${{ steps.detect.outputs.files }}
          HAS_SKIP: \${{ steps.skip-check.outputs.has_skip }}
        with:
          script: |
            const hasDestructive = process.env.HAS_DESTRUCTIVE === 'true';
            const validationPassed = process.env.VALIDATION_PASSED === 'true';
            const hasSkip = process.env.HAS_SKIP === 'true';
            const files = JSON.parse(process.env.FILES || '[]');
            const body = [
              '## Supabase Migration Validation',
              '',
              '**Migration Files Changed:**',
              ...files.map(f => '- ' + f),
              '',
              '| Check | Result |',
              '|-------|--------|',
              '| SQL Syntax | ' + (validationPassed ? 'Valid' : 'FAILED') + ' |',
              '| Destructive Ops | ' + (hasDestructive ? 'DETECTED' : 'None') + ' |',
              '| Skip Files | ' + (hasSkip ? 'Present' : 'None') + ' |',
              '',
              hasDestructive
                ? 'WARNING: This migration contains destructive operations. Manual review required before merge.'
                : 'Migration appears safe to apply.',
              '',
              '*Automated by UGWTF Supabase Migration Automation*'
            ].join('\\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
            const labels = hasDestructive
              ? ['database', 'needs-review', 'destructive-migration']
              : ['database', 'safe-migration'];
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });

      - name: Block merge if destructive
        if: steps.safety.outputs.has_destructive == 'true'
        run: |
          echo "BLOCKING: Destructive migration detected"
          echo "Manual review required before merge"
          exit 1

  # Phase 2: Apply Migration (runs after merge to main)
  apply-migration:
    name: Apply Migration
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/${repo.defaultBranch}'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${repo.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Detect new migrations
        id: detect
        run: |
          FILES=\$(git diff --name-only HEAD~1 HEAD | grep 'supabase/migrations/.*\\.sql\$' | grep -v '.skip\$' || true)
          if [ -z "\$FILES" ]; then
            echo "No new migrations to apply"
            echo "has_migrations=false" >> \$GITHUB_OUTPUT
            exit 0
          fi
          FILES_JSON=\$(echo "\$FILES" | jq -R -s -c 'split("\\n") | map(select(length > 0))')
          echo "migrations=\$FILES_JSON" >> \$GITHUB_OUTPUT
          echo "has_migrations=true" >> \$GITHUB_OUTPUT

      - name: Apply migrations via REST API
        if: steps.detect.outputs.has_migrations == 'true'
        env:
          SUPABASE_URL: \${{ secrets.${urlSecretName} }}
          SUPABASE_SERVICE_ROLE_KEY: \${{ secrets.${serviceKeySecretName} }}
          MIGRATIONS: \${{ steps.detect.outputs.migrations }}
        run: |
          echo "\$MIGRATIONS" | jq -r '.[]' | while read -r file; do
            echo "Applying migration: \$file"
            if [ -f "scripts/apply-migration-via-rest.cjs" ]; then
              node scripts/apply-migration-via-rest.cjs "\$file"
            else
              SQL_CONTENT=\$(cat "\$file")
              curl -X POST "\${SUPABASE_URL}/rest/v1/rpc/exec_sql" \\
                -H "apikey: \${SUPABASE_SERVICE_ROLE_KEY}" \\
                -H "Authorization: Bearer \${SUPABASE_SERVICE_ROLE_KEY}" \\
                -H "Content-Type: application/json" \\
                -d "{\\"query\\": \$(echo "\$SQL_CONTENT" | jq -Rs .)}"
            fi
            echo "Applied migration: \$file"
          done

      - name: Regenerate TypeScript types
        if: steps.detect.outputs.has_migrations == 'true'
        env:
          SUPABASE_ACCESS_TOKEN: \${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase gen types typescript \\
            --project-id ${repo.supabaseProjectId} \\
            > ${typesPath}

      - name: Run TypeScript check
        if: steps.detect.outputs.has_migrations == 'true'
        run: npx tsc --noEmit

      - name: Create PR with regenerated types
        if: steps.detect.outputs.has_migrations == 'true'
        uses: actions/github-script@v7
        env:
          MIGRATIONS: \${{ steps.detect.outputs.migrations }}
        with:
          script: |
            const migrations = JSON.parse(process.env.MIGRATIONS || '[]');
            const { execSync } = require('child_process');
            const hasChanges = execSync('git status --porcelain ${typesPath}').toString().trim();
            if (!hasChanges) {
              console.log('No type changes detected');
              return;
            }
            const branchName = 'automation/types-update-' + Date.now();
            execSync('git checkout -b ' + branchName);
            execSync('git add ${typesPath}');
            execSync('git config user.name "github-actions[bot]"');
            execSync('git config user.email "github-actions[bot]@users.noreply.github.com"');
            execSync('git commit -m "chore: Regenerate Supabase types after migration"');
            execSync('git push origin ' + branchName);
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update Supabase Types After Migration',
              head: branchName,
              base: '${repo.defaultBranch}',
              body: [
                '## Automated Type Regeneration',
                '',
                'TypeScript types regenerated after applying:',
                ...migrations.map(m => '- ' + m),
                '',
                '*Created by UGWTF Supabase Migration Automation.*'
              ].join('\\n')
            });
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['automation:copilot', 'database', 'types-update']
            });

  # Phase 3: Failure Handling
  handle-failure:
    name: Migration Failed
    runs-on: ubuntu-latest
    if: failure() && github.event_name == 'push'
    permissions:
      issues: write

    steps:
      - name: Create incident issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'URGENT: Database Migration Failed',
              body: [
                '## CRITICAL: Migration Application Failed',
                '',
                'Workflow Run: ' + context.serverUrl + '/' + context.repo.owner + '/' + context.repo.repo + '/actions/runs/' + context.runId,
                'Commit: ' + context.sha,
                '',
                '**IMMEDIATE ACTIONS:**',
                '1. Check workflow logs for error details',
                '2. Verify database state: npx supabase db diff',
                '3. Check for partial migration application',
                '4. Manually roll back if necessary',
                '5. Fix migration file and re-apply',
                '',
                'Database may be in inconsistent state. Investigate immediately.'
              ].join('\\n'),
              labels: ['priority:p0', 'database', 'incident', 'needs-review']
            });
`;
}
