/**
 * Visual Audit Workflow Generator
 *
 * Runs @dabighomie/audit-orchestrator on PRs that touch source files.
 * Posts audit score + top issues as a PR comment.
 */
import type { RepoConfig } from '../config/repo-registry.js';

export function generateVisualAudit(repo: RepoConfig): string {
  return `# Auto-generated by @dabighomie/ugwtf — do not edit manually
name: Visual Audit

on:
  pull_request:
    branches:
      - ${repo.defaultBranch}
    paths:
      - 'src/**'
      - 'app/**'
      - '**/*.tsx'
      - '**/*.css'

permissions:
  contents: read
  pull-requests: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${repo.nodeVersion}
      - run: npx @dabighomie/audit-orchestrator --json > audit-results.json
      - name: Post audit results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const raw = fs.readFileSync('audit-results.json', 'utf8');
            const result = JSON.parse(raw);
            const score = result.overallCompletion;
            const icon = score >= 80 ? ':white_check_mark:' : score >= 50 ? ':warning:' : ':x:';
            const issues = result.issues || [];
            const critical = issues.filter(i => i.severity === 'critical').length;
            const high = issues.filter(i => i.severity === 'high').length;
            const medium = issues.filter(i => i.severity === 'medium').length;
            const low = issues.filter(i => i.severity === 'low').length;

            let body = '## ' + icon + ' Visual Audit: ' + score + '%\\n\\n';
            body += '| Metric | Value |\\n|--------|-------|\\n';
            body += '| Score | **' + score + '%** |\\n';
            body += '| Critical | ' + critical + ' |\\n';
            body += '| High | ' + high + ' |\\n';
            body += '| Medium | ' + medium + ' |\\n';
            body += '| Low | ' + low + ' |\\n';
            body += '| Total Issues | ' + issues.length + ' |\\n\\n';

            if (issues.length > 0) {
              body += '### Top Issues\\n\\n';
              const sevIcon = { critical: ':red_circle:', high: ':orange_circle:', medium: ':yellow_circle:', low: ':green_circle:' };
              for (const issue of issues.slice(0, 10)) {
                const sev = sevIcon[issue.severity] || ':white_circle:';
                body += '- ' + sev + ' **' + issue.id + '**: ' + issue.title + '\\n';
              }
              if (issues.length > 10) {
                body += '\\n_...and ' + (issues.length - 10) + ' more._\\n';
              }
            }

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const existing = comments.find(c => c.body && c.body.includes('Visual Audit:'));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: audit-results
          path: audit-results.json
`;
}
