#!/usr/bin/env npx tsx
/**
 * create-chain-issues.mts — Portable script to create GitHub issues from prompt-chain.json
 *
 * Usage:
 *   npx tsx scripts/create-chain-issues.mts <path-to-prompt-chain.json> [--dry-run] [--kick]
 *
 * Options:
 *   --dry-run   Preview issues without creating them
 *   --kick      After creating issues, assign Copilot to position 1
 *
 * Example:
 *   npx tsx scripts/create-chain-issues.mts projects/o43/prompt-chain.json --dry-run
 *   npx tsx scripts/create-chain-issues.mts projects/o43/prompt-chain.json --kick
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ChainEntry {
  position: number;
  prompt: string;
  file: string;
  wave: number;
  severity: string;
  depends: string[];
  issue: number | null;
}

interface ChainConfig {
  version: number;
  description: string;
  repo: string;
  labels: string[];
  chain: ChainEntry[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function severityToLabel(severity: string): string {
  const map: Record<string, string> = {
    critical: 'priority:p0',
    high: 'priority:p1',
    medium: 'priority:p2',
    low: 'priority:p3',
  };
  return map[severity] ?? 'priority:p2';
}

function buildBody(entry: ChainEntry, config: ChainConfig): string {
  const deps = entry.depends.length > 0
    ? entry.depends.map(d => {
        const dep = config.chain.find(e => e.prompt === d);
        return dep?.issue ? `- #${dep.issue} (${d})` : `- ${d}`;
      }).join('\n')
    : '_None_';

  return [
    `## Prompt Chain — Position ${entry.position}/${config.chain.length}`,
    '',
    `**Prompt**: \`${entry.prompt}\``,
    `**File**: \`${entry.file}\``,
    `**Wave**: ${entry.wave} | **Severity**: ${entry.severity}`,
    '',
    '### Dependencies',
    deps,
    '',
    '### Instructions',
    `Read the prompt file at \`${entry.file}\` and implement all changes described.`,
    '',
    '---',
    '_Auto-generated by UGWTF create-chain-issues script_',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const configPath = args.find(a => !a.startsWith('--'));
const dryRun = args.includes('--dry-run');
const kick = args.includes('--kick');

if (!configPath) {
  console.error('Usage: npx tsx scripts/create-chain-issues.mts <path-to-prompt-chain.json> [--dry-run] [--kick]');
  process.exit(1);
}

const config: ChainConfig = JSON.parse(readFileSync(configPath, 'utf-8'));
const missing = config.chain.filter(e => e.issue === null);

console.log(`\nRepo: ${config.repo}`);
console.log(`Total chain entries: ${config.chain.length}`);
console.log(`Missing issues: ${missing.length}`);
console.log(`Dry run: ${dryRun}\n`);

if (missing.length === 0) {
  console.log('All chain entries already have issues. Nothing to do.');
  process.exit(0);
}

let created = 0;

for (const entry of missing) {
  const title = `[Chain ${entry.position}/${config.chain.length}] ${entry.prompt}: ${entry.file.split('/').pop()?.replace('.prompt.md', '') ?? entry.prompt}`;
  const body = buildBody(entry, config);
  const labels = [...config.labels, severityToLabel(entry.severity)].join(',');

  if (dryRun) {
    console.log(`  [DRY] Would create: "${title}"`);
    console.log(`         Labels: ${labels}`);
    created++;
    continue;
  }

  try {
    const result = execSync(
      `gh issue create --repo "${config.repo}" --title "${title.replace(/"/g, '\\"')}" --body "${body.replace(/"/g, '\\"')}" --label "${labels}"`,
      { encoding: 'utf-8', timeout: 30000 }
    ).trim();

    // Extract issue number from URL
    const issueNum = parseInt(result.split('/').pop() ?? '0');
    if (issueNum > 0) {
      const idx = config.chain.findIndex(e => e.position === entry.position);
      if (idx !== -1) config.chain[idx].issue = issueNum;
      console.log(`  Created #${issueNum}: ${entry.prompt} (pos ${entry.position})`);
      created++;
    }
  } catch (err) {
    console.error(`  ERROR creating issue for ${entry.prompt}: ${err instanceof Error ? err.message : String(err)}`);
  }
}

// Write back updated config
if (!dryRun && created > 0) {
  writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  console.log(`\nUpdated ${configPath} with ${created} issue numbers`);
}

// Kick: assign Copilot to position 1
if (kick && !dryRun) {
  const first = config.chain.find(e => e.position === 1);
  if (first?.issue) {
    console.log(`\nKicking chain: assigning Copilot to #${first.issue}...`);
    try {
      execSync(
        `gh issue edit ${first.issue} --repo "${config.repo}" --add-label "automation:in-progress"`,
        { encoding: 'utf-8', timeout: 15000 }
      );
      console.log(`  Added automation:in-progress label to #${first.issue}`);
    } catch (err) {
      console.error(`  WARNING: Could not kick chain: ${err instanceof Error ? err.message : String(err)}`);
      console.error('  Use mcp_github2_assign_copilot_to_issue to assign Copilot manually');
    }
  }
}

console.log(`\nDone. Created ${created} issues.`);
